--insert into client(id_cliente, nome, renda)
--values(1, 'elias oliveira', 8000.00);
--
--insert into cliente(id_cliente, nome, renda)
--values(2, 'will smith', 3000.98);
--
--insert into cliente(id_cliente, nome, renda)
--values(3, 'alice nunes', 1000.33);